### ISSUE TITLE
フォント変更時にAviUtlが落ちることがある

### ISSUE THREAD

**Issue by karoterra** [oov/aviutl_textassist#1]
テキストオブジェクトが以下のような状態でフォント名にカーソルを合わせ、<kbd><kbd>Alt</kbd>+<kbd>↑</kbd></kbd>を押すとAviUtlが落ちることがあります。
落ちない場合はフォント名が空欄になったりフォント名でない文字列になったりしました。

```
あい<s32,ＭＳ Ｐ明朝,>うえお
```

確認したところ、`wcscpy` に無効なアドレスを渡して落ちているようです。
https://github.com/oov/aviutl_textassist/blob/7cbe646240dfe9ace9993efaf373dcf5a7bbd9ce/src/textassist.c#L488

**環境**
- Windows 11
- AviUtl version 1.10
- 拡張編集 version 0.92
- テキスト編集補助 v0.3.4 ( 7cbe646 )

**Comment by oov** [comment]
ご報告ありがとうございます。
確かに配列の範囲外にアクセスできてしまうのを確認しました。

**Comment by oov** [comment]
修正版をリリースしました。
的確なご報告大変助かりました、ありがとうございます。
