### ISSUE TITLE
ウェイト時のショートカットコマンドに制限がある

### ISSUE THREAD

**Issue by toreron4990** [oov/aviutl_textassist#2]
表示ウェイトの<w1>をこちらのプラグインを利用して調整する際
ALT＋↑で数値を上げると2.1で止まってしまう。

また、それ以上に数値を主導で上げた際もALT＋↓で下がることはできるのに
ALT＋↑で数値を上げることができません。

こちらは私の環境依存でしょうか？
プラグイン同居環境の列挙も多すぎるので私だけの環境問題でしたら諦めます。

**Comment by oov** [comment]
長らくお返事できず申し訳ありませんでした。
https://github.com/oov/aviutl_textassist/pull/3 でこの問題を修正頂いたので、次回のリリースからは起こらなくなるはずです。

**Comment by oov** [comment]
[v0.3.6](https://github.com/oov/aviutl_textassist/releases/tag/v0.3.6) に修正が含まれていますので、アップデートをよろしくお願いいたします。
